In [1]:
import numpy as np
import pandas as pd

In [2]:
from datetime import date, timedelta, datetime

In [3]:
url = "https://raw.githubusercontent.com/leotraeg/FHDTM-P2DS-WS2425/refs/heads/main/Demo/Datensaetze/FHDTM-P2DS-WS2425-Project-Demo-1.2-Data-Acquisition-Transfermarkt_Top_100.csv"
df_players = pd.read_csv(url)

In [4]:
df_players

,club_name,club_number_player,club_avg_age,club_league,club_number_foreign_players,club_number_national_players,club_stadium,club_stadium_seats,club_current_transfer_balance,player_position,player_number,player_name,player_dob,player_country,player_value
0,Manchester City,27,"26,3",Premier League,17,19,Etihad Stadium,55.017 Plätze,"-79,10 Mio. €",Torwart,31,Ederson,17.08.1993 (29),Brasilien,"40,00 Mio. €"
1,Manchester City,27,"26,3",Premier League,17,19,Etihad Stadium,55.017 Plätze,"-79,10 Mio. €",Torwart,18,Stefan Ortega,06.11.1992 (30),Deutschland,"9,00 Mio. €"
2,Manchester City,27,"26,3",Premier League,17,19,Etihad Stadium,55.017 Plätze,"-79,10 Mio. €",Torwart,13,Zack Steffen,02.04.1995 (28),Vereinigte Staaten,"3,50 Mio. €"
3,Manchester City,27,"26,3",Premier League,17,19,Etihad Stadium,55.017 Plätze,"-79,10 Mio. €",Torwart,33,Scott Carson,03.09.1985 (37),England,200 Tsd. €
4,Manchester City,27,"26,3",Premier League,17,19,Etihad Stadium,55.017 Plätze,"-79,10 Mio. €",Abwehr,3,Rúben Dias,14.05.1997 (26),Portugal,"80,00 Mio. €"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2937,AZ Alkmaar,31,"23,0",Eredivisie,12,6,AFAS Stadion,19.478 Plätze,"+36,17 Mio. €",Sturm,9,Vangelis Pavlidis,21.11.1998 (24),Griechenland,"14,00 Mio. €"
2938,AZ Alkmaar,31,"23,0",Eredivisie,12,6,AFAS Stadion,19.478 Plätze,"+36,17 Mio. €",Sturm,29,Mexx Meerdink,24.07.2003 (20),Niederlande,"1,50 Mio. €"
2939,AZ Alkmaar,31,"23,0",Eredivisie,12,6,AFAS Stadion,19.478 Plätze,"+36,17 Mio. €",Sturm,17,Yusuf Barasi,31.03.2003 (20),Türkei,600 Tsd. €
2940,AZ Alkmaar,31,"23,0",Eredivisie,12,6,AFAS Stadion,19.478 Plätze,"+36,17 Mio. €",Sturm,21,Ernest Poku,28.01.2004 (19),Niederlande,600 Tsd. €
2941,AZ Alkmaar,31,"23,0",Eredivisie,12,6,AFAS Stadion,19.478 Plätze,"+36,17 Mio. €",Sturm,-,Jelle Duin,27.01.1999 (24),Niederlande,350 Tsd. €

In [5]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2942 entries, 0 to 2941
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   club_name                      2942 non-null   object
 1   club_number_player             2942 non-null   int64
 2   club_avg_age                   2942 non-null   object
 3   club_league                    2942 non-null   object
 4   club_number_foreign_players    2942 non-null   int64
 5   club_number_national_players   2942 non-null   int64
 6   club_stadium                   2942 non-null   object
 7   club_stadium_seats             2942 non-null   object
 8   club_current_transfer_balance  2942 non-null   object
 9   player_position                2942 non-null   object
 10  player_number                  2942 non-null   object
 11  player_name                    2942 non-null   object
 12  player_dob                     2942 non-null   object
 13  player_country                 2942 non-null   object
 14  player_value                   2919 non-null   object
dtypes: int64(3), object(12)
memory usage: 344.9+ KB

# Data Preprocessing

## Data Cleaning

In [6]:
#Pandas read function casts club_avg_age as object -> cast data type for club_avg_age as float
df_players.club_avg_age = df_players.club_avg_age.str.replace(",",".").astype(float)

In [7]:
#club_stadium_seats non numeric format (e.g. 55.017 Plätze) -> transform club_stadium_seats as int (e.g. 55017)
df_players.club_stadium_seats = df_players.club_stadium_seats.apply(lambda x: int(float(x.split()[0])*1000))

In [8]:
#club_current_transfer_balance non numeric format (e.g. -79,10 Mio. €) -> transform club_current_transfer_balance as float (e.g. -79100000.00)
def get_club_transfer_balance_numeric(club_transfer_balance):
    if(type(club_transfer_balance) == float):
      return club_transfer_balance
    else:
      club_transfer_balance_arr = club_transfer_balance.split(" ")
      #"-128,00 Mio. €".split(" ") --> ['-128,00', 'Mio.', '€']
      value = club_transfer_balance_arr[0].replace(",",".").replace("+","")
      return float(float(value)*1000000)

In [9]:
df_players.club_current_transfer_balance = df_players.club_current_transfer_balance.apply(get_club_transfer_balance_numeric)

In [10]:
#player_number non numeric format as some players have no number (e.g. "-") -> set players without number = 0
df_players.player_number = df_players.player_number.replace("-", 0).astype(int)

In [11]:
#player_dob_date contains dob and age
def get_player_age(player_dob):
    player_dob_arr = player_dob.split(" ")
    #"06.12.1997 (25)".split(" ") --> ['06.12.1997', '(25)']
    age = player_dob_arr[1].replace("(","").replace(")","")
    return age

In [12]:
df_players["player_age"] = df_players.player_dob.apply(get_player_age).astype(int)

In [13]:
#player_dob_date contains dob and age
def get_player_dob_date(player_dob):
    if(type(player_dob) == datetime.date):
      return player_dob
    else:
      player_dob_arr = player_dob.split(" ")
      #"06.12.1997 (25)".split(" ") --> ['06.12.1997', '(25)']
      dob_arr = player_dob_arr[0].split(".")
      return date(int(dob_arr[2]), int(dob_arr[1]), int(dob_arr[0]))

In [14]:
df_players.player_dob = df_players.player_dob.apply(get_player_dob_date)

In [15]:
#player_value non numeric format (e.g. -79,10 Mio. €) -> transform player_value as float (e.g. -79100000.00)
def get_player_value_numeric(player_value):
    if(type(player_value) == float):
      return player_value
    else:
      player_value_arr = player_value.split(" ")
      #"150 Tsd. €".split(" ") --> ['150,00', 'Tsd.', '€']
      value = player_value_arr[0].replace(",",".")
      unit = 1000 if "Tsd." in player_value_arr[1] else 1000000
      return float(float(value)*unit)

In [16]:
df_players.player_value = df_players.player_value.apply(get_player_value_numeric)

In [17]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2942 entries, 0 to 2941
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   club_name                      2942 non-null   object
 1   club_number_player             2942 non-null   int64
 2   club_avg_age                   2942 non-null   float64
 3   club_league                    2942 non-null   object
 4   club_number_foreign_players    2942 non-null   int64
 5   club_number_national_players   2942 non-null   int64
 6   club_stadium                   2942 non-null   object
 7   club_stadium_seats             2942 non-null   int64
 8   club_current_transfer_balance  2942 non-null   float64
 9   player_position                2942 non-null   object
 10  player_number                  2942 non-null   int32
 11  player_name                    2942 non-null   object
 12  player_dob                     2942 non-null   object
 13  player_country                 2942 non-null   object
 14  player_value                   2919 non-null   float64
 15  player_age                     2942 non-null   int32
dtypes: float64(3), int32(2), int64(4), object(7)
memory usage: 344.9+ KB

In [18]:
df_players

,club_name,club_number_player,club_avg_age,club_league,club_number_foreign_players,club_number_national_players,club_stadium,club_stadium_seats,club_current_transfer_balance,player_position,player_number,player_name,player_dob,player_country,player_value,player_age
0,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,Torwart,31,Ederson,1993-08-17,Brasilien,40000000.0,29
1,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,Torwart,18,Stefan Ortega,1992-11-06,Deutschland,9000000.0,30
2,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,Torwart,13,Zack Steffen,1995-04-02,Vereinigte Staaten,3500000.0,28
3,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,Torwart,33,Scott Carson,1985-09-03,England,200000.0,37
4,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,Abwehr,3,Rúben Dias,1997-05-14,Portugal,80000000.0,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2937,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Sturm,9,Vangelis Pavlidis,1998-11-21,Griechenland,14000000.0,24
2938,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Sturm,29,Mexx Meerdink,2003-07-24,Niederlande,1500000.0,20
2939,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Sturm,17,Yusuf Barasi,2003-03-31,Türkei,600000.0,20
2940,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Sturm,21,Ernest Poku,2004-01-28,Niederlande,600000.0,19
2941,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Sturm,0,Jelle Duin,1999-01-27,Niederlande,350000.0,24

In [19]:
df_players.describe()

,club_number_player,club_avg_age,club_number_foreign_players,club_number_national_players,club_stadium_seats,club_current_transfer_balance,player_number,player_value,player_age
count,2942.000000,2942.000000,2942.000000,2942.000000,2942.000000,2.942000e+03,2942.000000,2.919000e+03,2942.000000
mean,30.018355,25.421176,16.111829,11.720938,44066.239633,-9.689878e+06,20.867777,1.057879e+07,25.421482
std,4.333316,1.322881,5.709451,4.805991,18378.115386,5.883865e+07,19.822774,1.556057e+07,4.569660
min,22.000000,21.300000,1.000000,3.000000,11329.000000,-1.977500e+08,0.000000,2.500000e+04,17.000000
25%,26.000000,24.400000,12.000000,8.000000,30150.000000,-2.832000e+07,7.000000,1.500000e+06,22.000000
50%,30.000000,25.400000,16.000000,11.000000,42372.000000,-3.600000e+06,17.000000,5.000000e+06,25.000000
75%,33.000000,26.300000,20.000000,15.000000,55600.000000,2.309000e+07,27.000000,1.300000e+07,29.000000
max,43.000000,28.300000,27.000000,22.000000,99354.000000,1.184000e+08,99.000000,1.800000e+08,42.000000

## Data Transformation

In [20]:
#attribute construction of international ratio of clubs
def club_internationality(number_player, number_foreign_players):
  foreign_ratio = number_foreign_players / number_player
  if foreign_ratio > 0.85:
    return "extremly international"
  elif foreign_ratio > 0.2:
    return "very international"
  else:
    return "international"

In [21]:
df_players["club_internationality"] = (df_players.apply(lambda x: club_internationality(x.club_number_player, x.club_number_foreign_players), axis=1))

In [22]:
#numeric scaling of player positions
df_players["player_position_scale"] = df_players.player_position.map({'Torwart': 1, 'Abwehr': 2, 'Mittelfeld': 3, 'Sturm':4, np.NaN:0})

In [23]:
#club leauge is linked to a specific country -> construct attribute of club country
df_players.club_league.unique()

array(['Premier League', 'Ligue 1', 'LaLiga', 'Bundesliga', 'Serie A',
       'Championship', 'Liga Portugal', 'Süper Lig', 'Eredivisie',
       'Saudi Pro League', 'Campeonato Brasileiro Série A',
       'Premier Liga', 'Jupiler Pro League', 'Scottish Premiership',
       'SuperSport HNL', 'Liga Profesional de Fútbol'], dtype=object)

In [24]:
dict_league_country = {'Premier League':"England",
                       'Ligue 1':"Frankreich",
                       'LaLiga':"Spanien",
                       'Bundesliga':"Deutschland",
                       'Serie A':"Italien",
                       'Championship':"England",
                       'Liga Portugal':"Portugal",
                       'Süper Lig':"Türkei",
                       'Eredivisie':"Niederlande",
                       'Saudi Pro League':"Saudi-Arabien",
                       'Campeonato Brasileiro Série A':"Brasilien",
                       'Premier Liga':"Russland",
                       'Jupiler Pro League':"Belgien",
                       'Scottish Premiership':"Schottland",
                       'SuperSport HNL':"Kroatien",
                       'Liga Profesional de Fútbol':"Argentinien"}

In [25]:
df_players["club_country"] = df_players.club_league.map(dict_league_country)

In [26]:
df_players["player_international"] = (df_players.apply(lambda x: 1 if x.player_country != x.club_country else 0, axis=1))

In [27]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2942 entries, 0 to 2941
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   club_name                      2942 non-null   object
 1   club_number_player             2942 non-null   int64
 2   club_avg_age                   2942 non-null   float64
 3   club_league                    2942 non-null   object
 4   club_number_foreign_players    2942 non-null   int64
 5   club_number_national_players   2942 non-null   int64
 6   club_stadium                   2942 non-null   object
 7   club_stadium_seats             2942 non-null   int64
 8   club_current_transfer_balance  2942 non-null   float64
 9   player_position                2942 non-null   object
 10  player_number                  2942 non-null   int32
 11  player_name                    2942 non-null   object
 12  player_dob                     2942 non-null   object
 13  player_country                 2942 non-null   object
 14  player_value                   2919 non-null   float64
 15  player_age                     2942 non-null   int32
 16  club_internationality          2942 non-null   object
 17  player_position_scale          2942 non-null   int64
 18  club_country                   2942 non-null   object
 19  player_international           2942 non-null   int64
dtypes: float64(3), int32(2), int64(6), object(9)
memory usage: 436.8+ KB

In [28]:
df_players

,club_name,club_number_player,club_avg_age,club_league,club_number_foreign_players,club_number_national_players,club_stadium,club_stadium_seats,club_current_transfer_balance,player_position,player_number,player_name,player_dob,player_country,player_value,player_age,club_internationality,player_position_scale,club_country,player_international
0,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,Torwart,31,Ederson,1993-08-17,Brasilien,40000000.0,29,very international,1,England,1
1,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,Torwart,18,Stefan Ortega,1992-11-06,Deutschland,9000000.0,30,very international,1,England,1
2,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,Torwart,13,Zack Steffen,1995-04-02,Vereinigte Staaten,3500000.0,28,very international,1,England,1
3,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,Torwart,33,Scott Carson,1985-09-03,England,200000.0,37,very international,1,England,0
4,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,Abwehr,3,Rúben Dias,1997-05-14,Portugal,80000000.0,26,very international,2,England,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2937,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Sturm,9,Vangelis Pavlidis,1998-11-21,Griechenland,14000000.0,24,very international,4,Niederlande,1
2938,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Sturm,29,Mexx Meerdink,2003-07-24,Niederlande,1500000.0,20,very international,4,Niederlande,0
2939,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Sturm,17,Yusuf Barasi,2003-03-31,Türkei,600000.0,20,very international,4,Niederlande,1
2940,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Sturm,21,Ernest Poku,2004-01-28,Niederlande,600000.0,19,very international,4,Niederlande,0
2941,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Sturm,0,Jelle Duin,1999-01-27,Niederlande,350000.0,24,very international,4,Niederlande,0

In [29]:
#create seperate clubs dataset
df_clubs = df_players[["club_name",	"club_number_player",	"club_avg_age",	"club_league",	"club_number_foreign_players",	"club_number_national_players",	"club_stadium",	"club_stadium_seats",	"club_current_transfer_balance", "club_country",	"club_internationality"]].copy()

In [30]:
df_clubs = df_clubs.drop_duplicates().reset_index(drop=True)

In [31]:
df_clubs

,club_name,club_number_player,club_avg_age,club_league,club_number_foreign_players,club_number_national_players,club_stadium,club_stadium_seats,club_current_transfer_balance,club_country,club_internationality
0,Manchester City,27,26.3,Premier League,17,19,Etihad Stadium,55017,-79100000.0,England,very international
1,FC Arsenal,33,24.7,Premier League,24,22,Emirates Stadium,60704,-197750000.0,England,very international
2,FC Paris Saint-Germain,39,25.3,Ligue 1,27,22,Parc des Princes,49691,-128000000.0,Frankreich,very international
3,Real Madrid,24,26.7,LaLiga,16,19,Santiago Bernabéu,81044,-124500000.0,Spanien,very international
4,FC Chelsea,30,23.8,Premier League,19,18,Stamford Bridge,40853,46900000.0,England,very international
...,...,...,...,...,...,...,...,...,...,...,...
95,Spartak Moskau,30,24.7,Premier Liga,10,13,Otkrytie Bank Arena,44571,-15000000.0,Russland,very international
96,Stade Reims,31,24.3,Ligue 1,23,10,Stade Auguste-Delaune,21684,6050000.0,Frankreich,very international
97,CA Paranaense,34,25.3,Campeonato Brasileiro Série A,7,4,Arena da Baixada,42372,6300000.0,Brasilien,very international
98,Trabzonspor,34,25.1,Süper Lig,15,13,Papara Park,40782,-4570000.0,Türkei,very international
99,AZ Alkmaar,31,23.0,Eredivisie,12,6,AFAS Stadion,19478,36170000.0,Niederlande,very international

## Data Output/Input

In [90]:
#url = r"path"
file_name = "FHDTM-P2DS-WS2324-Project-Demo-2.0-Data-Preprocessing-Transfermarkt_Top_100.csv"
df_players.to_csv(url+file_name, index=False)

In [ ]:
#url = r"path"
file_name = "FHDTM-P2DS-WS2324-Project-Demo-2.0-Data-Preprocessing-Transfermarkt_Top_100_clubs.csv"
df_clubs.to_csv(url+file_name, index=False)