# Comparison and Logical Operators

In [ ]:
#< 			less than
#<= 		less than or equal to
#> 			greater than
#>= 		greater than or equal to
#==		  equal
#!= 		not equal
#and 		both must be true
#or 		one or both must be true
#not 		reverses the truth value

##Control Statements

In [ ]:
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
elif a > 201 or not( b > 33):
  print("something else")
else:
  print("a is greater than b")

##Training #1

In [ ]:
from random import randint as ri

In [ ]:
start_range = 0
end_range = 10
ri(start_range, end_range)

#Containers / Collections
- How can we store multiple data elements in Python?
- How can we access these?

##List [ ]
A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
x_list = ["Zuckerberg", "Musk", 42]    # Create a list
print(x_list, x_list[2])  # Prints "['Zuckerberg', 'Musk', 42] 42"
print(x_list[-1])     # Negative indices count from the end of the list;
                      # prints "42"
x_list[2] = 'Gates'   # Lists can contain elements of different types
print(x_list)         # Prints "['Zuckerberg', 'Musk', 'Gates']"
x_list.append('Bezos')# Add a new element to the end of the list
print(x_list)         # Prints "['Zuckerberg', 'Musk', 'Gates', 'Bezos']"
x = x_list.pop()      # Remove and return the last element of the list
print(x, x_list)      # Prints "Bezos ['Zuckerberg', 'Musk', 'Gates']"

More list methods append(), clear(), copy(), count(), extend(), index(), insert(), pop(), remove(), reverse(), sort() to find in documentation https://docs.python.org/3.5/tutorial/datastructures.html#more-on-lists

###List[ ] Slicing
In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [ ]:
nums = list(range(5))     # range is a function creating a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive);
                          # prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end;
                          # prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive);
                          #  prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list;
                          # prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative;
                          # prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]

###Loop
You can loop over the elements of a list like this

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey

If you want access to the index of each element within the body of a loop, use the built-in enumerate function:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

#1: cat
#2: dog
#3: monkey

###List Comprehensions
Frequently, we want to transform one type of data into another, e.g., price / square

In [ ]:
square_meters = [30, 40, 50, 60, 70]
square_prices = []
for square_meter in square_meters:
    square_prices.append(square_meter * 12)
print(square_prices)   # Prints [360, 480, 600, 720, 840]

[360, 480, 600, 720, 840]

You can make this code simpler using a list comprehension:

In [ ]:
square_meters = [30, 40, 50, 60, 70]
square_prices = [x * 12 for x in square_meters]
print(square_prices)   # Prints [360, 480, 600, 720, 840]

[360, 480, 600, 720, 840]

List comprehensions can also contain conditions:

In [ ]:
square_meters = [30, 40, 50, 60, 70]
square_prices = [x * 15 for x in square_meters if x < 51]
print(square_prices)  # Prints "[450, 600, 750]"

[450, 600, 750]

##Tuple ( )
- Consists of heterogenous sequences and values separated by commas
- Unchangeable ordered list of values

In [ ]:
t = ('Zuckerberg', 42, 'Gates', 'Bezos') # Create a tuple
print(type(t))   # Prints "<class 'tuple'>"
print(t.count('Zuckerberg')) # Prints "1"
print(t.index('Zuckerberg')) # Prints "0"
print(t[0])                  # Prints "Zuckerberg"
# Tuples may be nested with heterogeneous sequences:
t2 = t, ('Musk','Cooper')
print(t2)        # Prints "(('Zuckerberg', 42, 'Gates', 'Bezos'),
                 #          ('Musk', 'Cooper'))"
t[1] = 'Musk'    #  TypeError: 'tuple' object does not support item assignment

Documentation: https://docs.python.org/3.5/tutorial/datastructures.html#tuples-and-sequences

##Set { }
- Unordered collection of distinct elements

In [ ]:
s = {'Zuckerberg', 42, 'Gates', 'Bezos'}
print('Zuckerberg' in s)  # Check if an element is in a set; prints "True"
print('Musk' in s)        # prints "False"
s.add('Musk')           # Add an element to a set
print('Musk' in s)      # Prints "True"
print(len(s))           # Number of elements in a set; prints "5"
s.add('Musk')           # Adding an existing element does nothing
print(len(s))           # Prints "5"
s.remove('Musk')        # Remove an element from a set
print(len(s))           # Prints "4"

- Iterating over a set has the same syntax as iterating over a list (loop, comprehensions)
- Since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set

In [ ]:
s = {'Zuckerberg', 42, 'Gates', 'Bezos', 'Musk'}
for idx, answer in enumerate(s):
    print('#%d: %s' % (idx + 1, answer))
# Prints
#1: Bezos
#2: Gates
#3: Zuckerberg
#4: Musk
#5: 42

More set methods add(), clear(), copy(), difference_update(), discard(), issubset(), issuperset(), remove(), union(), update() to find in documentation https://docs.python.org/3.5/library/stdtypes.html#set

##Dictionary {"itemA":"itemB"}
A dictionary stores (key, value) pairs

In [ ]:
d = {'Tsd.': '000', 'Mil.': '000000'}  # Create a new dictionary with some data
print(d['Tsd.'])       # Get an entry from a dictionary; prints "000"
print('Tsd.' in d)     # Check if a dictionary has a given key; prints "True"
d['Bil.'] = '000000000'      # Set an entry in a dictionary
print(d['Bil.'])             # Prints "000000000"
#print(d['Tril.'])           # KeyError: 'Tril.' not a key of d
print(d.get('Tril.', 'N/A')) # Get an element with a default; prints "N/A"
print(d.get('Bil.', 'N/A'))  # Get an element with a default; prints "000000000"
del d['Bil.']                # Remove an element from a dictionary
print(d.get('Bil.', 'N/A'))  # "Bil." is no longer a key; prints "N/A"

You can loop over the keys in a dictionary:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs

If you want access to keys and their corresponding values, use the items method:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs

More dictionary methods clear(), copy(), fromkeys(), get(), items(), keys(), pop(), popitem(), setdefault(), update(), values() and dictionary comprehensions can be found in the documentation https://docs.python.org/3.5/library/stdtypes.html#dict

# Functions

In [ ]:
def isClassPassed(numberOfPoints):
    if numberOfPoints >= 50:
        return 'passed'
    else:
        return 'failed'

In [ ]:
for pointsScored in [55, 12, 66, 1, 99]:
    print(isClassPassed(pointsScored))
#Prints "passed, failed, passed, failed, passed"

In [ ]:
#Here's an extended template from Spyder.
def func(x, y = 0, *z, **j):
    """
    Describe your function's purpose concisely.
    Parameters
    ----------
    x : TYPE  DESCRIPTION.
    y : TYPE, optional DESCRIPTION. The default is 0.
    z : TYPE, arbitrary tuple of arguments.
    (If unkown/changing number of arguments)
    j : TYPE, arbitrary keyword arguments.

    Returns
    ----------

    """

## ...with List Comprehensions

In [ ]:
scoredPoints = [55, 12, 66, 1, 99];
classPassed = [isClassPassed(x) for x in scoredPoints]
print(classPassed)
#Prints "['passed', 'failed', 'passed', 'failed', 'passed']"

In [ ]:
scoredPoints = [55, 12, 66, 1, 99, 300, -1];
classPassed = [isClassPassed(x) for x in scoredPoints if x in range(100)]
print(classPassed)
#Prints "['passed', 'failed', 'passed', 'failed', 'passed']"

##Training #2 Hints

In [ ]:
from random import randint as ri

In [ ]:
points = [ri(0,116) for x in range(100)]

In [ ]:
points = []
for i in range(100):
  points.append(ri(0,116))

In [ ]:
def isClassPassed(numberOfPoints):
    if numberOfPoints >= 85:
        return 1
    else:
        return 'failed'

In [ ]:
print(points)

[97, 42, 46, 18, 56, 32, 97, 100, 30, 36, 65, 63, 13, 104, 0, 94, 64, 21, 14, 48, 18, 41, 6, 43, 87, 80, 100, 84, 52, 15, 6, 113, 59, 89, 25, 66, 89, 76, 20, 88, 8, 92, 112, 115, 62, 16, 87, 25, 5, 39, 35, 115, 23, 62, 20, 114, 61, 94, 13, 63, 79, 109, 19, 64, 33, 12, 17, 60, 11, 113, 3, 86, 61, 4, 62, 114, 115, 11, 73, 105, 25, 97, 53, 111, 16, 21, 114, 80, 42, 59, 75, 65, 34, 100, 78, 94, 61, 33, 100, 63]

In [ ]:
points_grade = []
for point in points:
  points_grade.append(isClassPassed(point))

In [ ]:
points_grade = [isClassPassed(x) for x in points]

In [ ]:
print(points_grade)

[1, 'failed', 'failed', 'failed', 'failed', 'failed', 1, 1, 'failed', 'failed', 'failed', 'failed', 'failed', 1, 'failed', 1, 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 1, 'failed', 1, 'failed', 'failed', 'failed', 'failed', 1, 'failed', 1, 'failed', 'failed', 1, 'failed', 'failed', 1, 'failed', 1, 1, 1, 'failed', 'failed', 1, 'failed', 'failed', 'failed', 'failed', 1, 'failed', 'failed', 'failed', 1, 'failed', 1, 'failed', 'failed', 'failed', 1, 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 1, 'failed', 1, 'failed', 'failed', 'failed', 1, 1, 'failed', 'failed', 1, 'failed', 1, 'failed', 1, 'failed', 'failed', 1, 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 1, 'failed', 1, 'failed', 'failed', 1, 'failed']

## ...with Map, Filter, and Reduce

###Map
- func is the function on which each element in iterables is applied on.
- The output is a map object containing a list.
- To get the result as a list, use the built-in list( ) function.

In [ ]:
scoredPoints = [55, 12, 66, 1, 99];
classPassed = list(map(isClassPassed, scoredPoints))
print(classPassed)
#Prints "['passed', 'failed', 'passed', 'failed', 'passed']"

['passed', 'failed', 'passed', 'failed', 'passed']

- What did we win? Flexibility and fault-tolerance.
- As the output of the map function is a map object.
- We can reuse it cascadingly.

In [ ]:
scoredPoints = [55, 12, 66, 1, 99];
classPassed2 = list(map(str.upper, map(isClassPassed, scoredPoints)))
print(classPassed2)
#Prints "['PASSED', 'FAILED', 'PASSED', 'FAILED', 'PASSED']"

['PASSED', 'FAILED', 'PASSED', 'FAILED', 'PASSED']

### Filter
- func is the function on which each element in iterable is filtered through.
- The output is a map object containing a list with only boolean = true filtered elements.
- To get the result as a list, use the built-in list( ) function.

In [ ]:
def onlyClassPassed(scoredPoints):
  return scoredPoints > 50

In [ ]:
scoredPoints = [55, 12, 66, 1, 99];
over50scoredPoints = list(filter(onlyClassPassed, scoredPoints))
print(over50scoredPoints)
#Prints "[55, 66, 99]"

[55, 66, 99]

### Reduce
- func is the function on which each element in the iterable gets cumulatively applied.
- initial is the optional value that gets placed before the elements of the iterable in the calculation and serves as a default when the iterable is empty.
- The output is a single value (name source: many values “reduced” to single).

In [ ]:
from functools import reduce

In [ ]:
def sumScoredPoints(scoredPointsA, scoredPointsB):
  return scoredPointsA + scoredPointsB

In [ ]:
scoredPoints = [55, 12, 66, 1, 99];
print(reduce(sumScoredPoints, scoredPoints))
#Prints "233"

233